---
- name: check for required fact ansible_network_os
  fail:
    msg: "missing required fact: ansible_network_os"
  when: ansible_network_os is undefined

- name: retrieve the current active (running) configuration
  get_config:
    source: running
    filter: "{{ config_filter | default(omit) }}"
  register: configuration
